// content/day-descriptions.ts
// Descriptions for each of the 60 stem-branch combinations

export const DAY_DESCRIPTIONS: Record<string, string> = {
  // Yang Wood (甲) Days
  "甲-子": "Bold new beginnings with strategic timing",
  "甲-丑": "Steady growth through patient effort",
  "甲-寅": "Courageous expansion and brave starts",
  "甲-卯": "Gentle growth and natural unfolding",
  "甲-辰": "Visionary projects and ambitious leaps",
  "甲-巳": "Thoughtful planning meets creative action",
  "甲-午": "Dynamic movement and enthusiastic starts",
  "甲-未": "Creative nurturing and artistic expression",
  "甲-申": "Clever innovation and playful problem-solving",
  "甲-酉": "Precise execution of new ideas",
  "甲-戌": "Loyal commitment to fresh directions",
  "甲-亥": "Generous beginnings and abundant optimism",
  
  // Yin Wood (乙) Days
  "乙-丑": "Gradual progress through gentle persistence",
  "乙-寅": "Adaptive courage and flexible strength",
  "乙-卯": "Soft resilience and peaceful growth",
  "乙-辰": "Graceful ambition and flowing vision",
  "乙-巳": "Subtle wisdom and elegant strategy",
  "乙-午": "Flexible momentum and adaptable energy",
  "乙-未": "Artistic sensitivity and refined creativity",
  "乙-申": "Smart flexibility and quick adjustments",
  "乙-酉": "Detailed refinement and careful crafting",
  "乙-戌": "Steady loyalty with room for change",
  "乙-亥": "Kind adaptability and flowing generosity",
  "乙-子": "Resourceful flexibility and clever growth",
  
  // Yang Fire (丙) Days
  "丙-寅": "Bold passion and fearless expression",
  "丙-卯": "Warm radiance and gentle confidence",
  "丙-辰": "Brilliant vision and powerful presence",
  "丙-巳": "Intense focus and magnetic energy",
  "丙-午": "Peak vitality and unstoppable momentum",
  "丙-未": "Creative fire and passionate artistry",
  "丙-申": "Bright enthusiasm and dynamic innovation",
  "丙-酉": "Clear brilliance and precise energy",
  "丙-戌": "Loyal passion and protective warmth",
  "丙-亥": "Generous spirit and open-hearted joy",
  "丙-子": "Sharp intelligence meets fiery drive",
  "丙-丑": "Sustained intensity and determined warmth",
  
  // Yin Fire (丁) Days
  "丁-卯": "Gentle warmth and subtle charm",
  "丁-辰": "Refined vision and elegant inspiration",
  "丁-巳": "Deep intensity and sophisticated passion",
  "丁-午": "Steady glow and enduring energy",
  "丁-未": "Artistic soul and creative refinement",
  "丁-申": "Clever charm and strategic warmth",
  "丁-酉": "Polished presence and meticulous care",
  "丁-戌": "Faithful warmth and trustworthy light",
  "丁-亥": "Nurturing glow and compassionate heart",
  "丁-子": "Perceptive warmth and intuitive spark",
  "丁-丑": "Patient dedication and lasting warmth",
  "丁-寅": "Contained passion and focused courage",
  
  // Yang Earth (戊) Days
  "戊-辰": "Powerful grounding and solid ambition",
  "戊-巳": "Wise foundation and strategic stability",
  "戊-午": "Dynamic reliability and active grounding",
  "戊-未": "Nurturing stability and supportive presence",
  "戊-申": "Practical innovation and grounded cleverness",
  "戊-酉": "Structured precision and organized strength",
  "戊-戌": "Unwavering loyalty and protective stability",
  "戊-亥": "Abundant foundation and generous support",
  "戊-子": "Strategic grounding and smart planning",
  "戊-丑": "Mountain-strong and unshakeable resolve",
  "戊-寅": "Bold stability and courageous foundation",
  "戊-卯": "Gentle strength and peaceful grounding",
  
  // Yin Earth (己) Days
  "己-巳": "Cultivated wisdom and nurtured insight",
  "己-午": "Grounded momentum and supportive action",
  "己-未": "Fertile creativity and artistic cultivation",
  "己-申": "Resourceful support and adaptive grounding",
  "己-酉": "Careful cultivation and detailed care",
  "己-戌": "Loyal support and faithful presence",
  "己-亥": "Rich nurturing and abundant care",
  "己-子": "Clever cultivation and smart support",
  "己-丑": "Deep patience and enduring nurture",
  "己-寅": "Supportive courage and gentle strength",
  "己-卯": "Soft care and peaceful cultivation",
  "己-辰": "Visionary support and elevated nurturing",
  
  // Yang Metal (庚) Days
  "庚-午": "Sharp action and clear momentum",
  "庚-未": "Refined creativity and precise artistry",
  "庚-申": "Brilliant innovation and sharp wit",
  "庚-酉": "Crystal clarity and perfect precision",
  "庚-戌": "Principled loyalty and clear conviction",
  "庚-亥": "Generous clarity and abundant focus",
  "庚-子": "Strategic sharpness and decisive thinking",
  "庚-丑": "Unyielding clarity and structured resolve",
  "庚-寅": "Bold decisiveness and courageous clarity",
  "庚-卯": "Gentle precision and refined focus",
  "庚-辰": "Visionary clarity and elevated precision",
  "庚-巳": "Penetrating insight and focused wisdom",
  
  // Yin Metal (辛) Days
  "辛-未": "Artistic refinement and delicate beauty",
  "辛-申": "Clever detail and polished innovation",
  "辛-酉": "Exquisite precision and perfected craft",
  "辛-戌": "Refined loyalty and elegant dedication",
  "辛-亥": "Polished generosity and refined grace",
  "辛-子": "Detailed intelligence and sharp perception",
  "辛-丑": "Patient craftsmanship and refined endurance",
  "辛-寅": "Elegant courage and refined strength",
  "辛-卯": "Delicate beauty and graceful precision",
  "辛-辰": "Refined vision and polished ambition",
  "辛-巳": "Sophisticated wisdom and elegant strategy",
  "辛-午": "Polished action and refined energy",
  
  // Yang Water (壬) Days
  "壬-申": "Deep cleverness and flowing innovation",
  "壬-酉": "Clear flow and precise intuition",
  "壬-戌": "Loyal depth and trustworthy instinct",
  "壬-亥": "Abundant flow and generous wisdom",
  "壬-子": "Deep intelligence and powerful intuition",
  "壬-丑": "Patient flow and enduring wisdom",
  "壬-寅": "Courageous depth and bold instinct",
  "壬-卯": "Gentle flow and peaceful intuition",
  "壬-辰": "Visionary depth and powerful current",
  "壬-巳": "Profound wisdom and deep insight",
  "壬-午": "Dynamic flow and active intuition",
  "壬-未": "Creative depth and artistic flow",
  
  // Yin Water (癸) Days
  "癸-酉": "Clear reflection and precise intuition",
  "癸-戌": "Faithful intuition and loyal insight",
  "癸-亥": "Pure wisdom and deep compassion",
  "癸-子": "Subtle intelligence and quiet knowing",
  "癸-丑": "Patient reflection and enduring wisdom",
  "癸-寅": "Intuitive courage and gentle strength",
  "癸-卯": "Soft reflection and peaceful knowing",
  "癸-辰": "Elevated intuition and visionary depth",
  "癸-巳": "Hidden wisdom and mysterious insight",
  "癸-午": "Flowing action and intuitive movement",
  "癸-未": "Artistic sensitivity and creative intuition",
  "癸-申": "Subtle cleverness and adaptive wisdom"
};
